<?php

declare(strict_types=1);

namespace Yiisoft\Yii\Queue\Middleware\Consume\Event;

use Yiisoft\Yii\Queue\Middleware\Push\MiddlewarePushInterface;
use Yiisoft\Yii\Queue\Middleware\Push\PushRequest;

/**
 * AfterMiddleware event is raised after a middleware was executed.
 */
final class AfterConsumeMiddleware
{
    /**
     * @param MiddlewarePushInterface $middleware Middleware that was executed.
     * @param PushRequest $request Response generated by middleware or null in case there was an error.
     */
    public function __construct(
        private MiddlewarePushInterface $middleware,
        private PushRequest $request
    ) {
    }

    /**
     * @return MiddlewarePushInterface Middleware that was executed.
     */
    public function getMiddleware(): MiddlewarePushInterface
    {
        return $this->middleware;
    }

    /**
     * @return PushRequest Response generated by middleware or null in case there was an error.
     */
    public function getRequest(): PushRequest
    {
        return $this->request;
    }
}
