<?php

declare(strict_types=1);

namespace Yiisoft\Yii\Queue\Middleware\Consume\Event;

use Yiisoft\Yii\Queue\Middleware\Consume\MiddlewareConsumeInterface;
use Yiisoft\Yii\Queue\Middleware\Consume\ConsumeRequest;

/**
 * AfterMiddleware event is raised after a middleware was executed.
 */
final class AfterConsumeMiddleware
{
    /**
     * @param MiddlewareConsumeInterface $middleware Middleware that was executed.
     * @param ConsumeRequest $request Response generated by middleware or null in case there was an error.
     */
    public function __construct(
        private MiddlewareConsumeInterface $middleware,
        private ConsumeRequest $request
    ) {
    }

    /**
     * @return MiddlewareConsumeInterface Middleware that was executed.
     */
    public function getMiddleware(): MiddlewareConsumeInterface
    {
        return $this->middleware;
    }

    /**
     * @return ConsumeRequest Response generated by middleware or null in case there was an error.
     */
    public function getRequest(): ConsumeRequest
    {
        return $this->request;
    }
}
