on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'
      - 'tests/**'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'
      - 'tests/**'

name: bechmark

jobs:
  phpbench:
    uses: yiisoft/actions/.github/workflows/phpbench.yml@phpbench-improvement
    with:
      os: >-
        ['ubuntu-latest', 'windows-latest']
      php: >-
        ['8.1', '8.2', '8.3']
      ref-name: master
    secrets:
      token: ${{ secrets.YIISOFT_GITHUB_TOKEN }}
