name: Rector + PHP CS Fixer

on:
  pull_request:
    paths:
      - 'config/**'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/rector-cs.yml'
      - 'composer.json'
      - 'rector.php'
      - '.php-cs-fixer.dist.php'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rector:
    permissions:
      contents: write # Required to push PHP CS Fixer and Rector changes back to the branch.
    uses: yiisoft/actions/.github/workflows/rector-cs.yml@50fd83c8ee9febc41032b8b97139dd89ba1c2f48
    with:
      php: '8.1'
